---
- name: shell
  hosts: localhost
  gather_facts: no
  tasks:

  - shell:
      cmd: /usr/local/bin/upgrade-database
    register: command_result
    changed_when: "'Success' in command_result.stdout"
    notify:
    - restart apache
  
  - debug:
      var: command_result

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: started
