---
- name: failed_when test
  hosts: localhost
  gather_facts: no
 
  tasks:

  - name: Run user creation script
    shell: /usr/local/bin/create_users.sh
    register: command_result
    failed_when: "'Password missing' in command_result.stdout"

  - debug:
      var: command_result.stdout

  - debug:
      msg: "Task 2"
