---
- name: Getting Variables from input file
  hosts: all
  gather_facts: no

  tasks:

  - debug:
      msg: 
        - "Name  {{ name }}"
        - "Std   {{ class }}"
        - "Days  {{ day }}"
        - "Month {{ month }}"
        - "Year  {{ year }}"


    
