---
- name: redhat | Enabling EPEL repo
  yum:
    name: ["epel-release"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing Pre-Reqs
  yum:
    name: ["lldpd", "screen"]
    state: present
  become: true
  register: result
  until: result is successful
  when: ansible_distribution != "Fedora"

- name: redhat | Installing bridge-utils
  yum:
    name: ["bridge-utils"]
  become: true
  register: result
  until: result is successful
  when: >
    config_network_bridges and
    ansible_distribution != "Fedora"

- name: redhat | Installing VLAN Packages
  yum:
    name: ["vconfig"]
    state: present
  become: true
  register: result
  until: result is successful
  when: >
    config_network_vlans and
    ansible_distribution != "Fedora"

- name: redhat | Enabling Bonding
  modprobe:
    name: bonding
    state: present
  become: true
  when: config_network_bonds

- name: redhat | Enabling Bridging
  modprobe:
    name: bridge
    state: present
  become: true
  when: config_network_bridges

- name: redhat | Configuring Interfaces
  template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
  register: config_interface
  become: true
  with_items: "{{ network_interfaces }}"
  when: >
    config_network_interfaces and
    item['configure']

- name: redhat | Configuring Bonds
  template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
  register: config_bond
  become: true
  with_items: "{{ network_bonds }}"
  when: >
    config_network_bonds and
    item['configure']

- name: redhat | Configuring Bridges
  template:
    src: etc/sysconfig/network-scripts/ifcfg.j2
    dest: "/etc/sysconfig/network-scripts/ifcfg-{{ item['name'] }}"
  register: config_bridge
  become: true
  with_items: "{{ network_bridges }}"
  when: >
    config_network_bridges and
    item['configure']

- name: redhat | Restarting Network Bonds
  shell: screen -dm bash -c "sleep {{ delay_before_restart }} && ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  with_items: "{{ config_bond['results'] }}"
  when: >
    config_network_bonds and
    (enable_configured_interfaces_after_defining or item['item']['enable']) and
    item['item']['configure'] and
    item['changed']

- name: redhat | Restarting Network Bridges
  shell: screen -dm bash -c "sleep {{ delay_before_restart }} && ifdown {{ item['item']['name'] }} && ifup {{ item['item']['name'] }}"
  become: true
  with_items: "{{ config_bridge['results'] }}"
  when: >
    config_network_bridges and
    (enable_configured_interfaces_after_defining or item['item']['enable']) and
    item['item']['configure'] and
    item['changed']

- name: redhat | Restarting Network Interfaces
  shell: screen -dm bash -c "sleep {{ delay_before_restart }} && ifdown {{ item['item']['name'] }} && sed -i '/{{ ansible_host }}/{/127.0.0.1/!d;}' /etc/hosts &&  echo '{{ item.address }}  $(hostname -f) $(hostname -s)' >> /etc/hosts && sleep 2  && service sssd restart"
  become: true
  with_items: "{{ config_interface['results'] }}"
  when: >
    config_network_interfaces and
    (enable_configured_interfaces_after_defining or item['item']['enable']) and
    item['item']['configure'] and
    item['changed']
