---
- name: uptime
  hosts: localhost
  gather_facts: no
  tasks:
  - shell: uptime
    register: runtime

  - debug:
      var: runtime

  - yum:
      name: httpd
      state: latest 
    register: yu

  - debug:
      var: yu
